//google fontları için kullanılır. yarn add @next/font şeklinde terminalden indirilebilir.
import { Inter } from "next/font/google";

/*
styles klasörü altındaki css leri import etmek için kullanılır.
Başındaki @ işareti ise jsconfig dosyasında belirrtiğimiz kodda @ gördüğü yeri nokta ile çevirir. Böylece uzun uzun path vermemize gerek kalmaz
*/
import "@/styles/reset.css";
import "@/styles/global.css";

//Eklemiş olduğumuz Header ve Footer componentlerini Layouta import ediyoruz.
import Header from "@/components/header/index.jsx";
import Footer from "@/components/footer/index.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container">
        {/* Header ve Footer componentini Body altında bu şekilde çağırıyoruz */}
        <Header />

        {/* children tag ı RenderBody ile aynıdır ve layout içerisinde gösterilecek sayfaların orada gösterileceğini gösterir */}
        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
export default RootLayout;
